working_directory = "None"

[colors.bright]
black = "#808080"
blue = "#0066ff"
cyan = "#00ffff"
green = "#00d900"
magenta = "#cc00ff"
red = "#fe0100"
white = "#FFFFFF"
yellow = "#feff00"

[colors.cursor]
cursor = "#ffffff"
text = "#F81CE5"

[colors.normal]
black = "#000000"
blue = "#0066ff"
cyan = "#00ffff"
green = "#00a600"
magenta = "#cc00ff"
red = "#fe0100"
white = "#d0d0d0"
yellow = "#feff00"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[cursor]
style = "Block"

[env]
TERM = "alacritty"

[font]
size = 9

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.normal]
family = "cozette"

[font.offset]
x = 1
y = 0

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "none"

[window.dimensions]
columns = 140
lines = 38

[window.padding]
x = 0
y = 0
